### ISSUE TITLE
support for inheritance?

### ISSUE THREAD

**Issue by pcompassion** [elado/jastor#3]
Any plan to support for inheritance?  

ProductCommon : jastor
{
commonAttributes;
}

Product1 : ProductCommon
{
product1_specific;
}

Product2 : ProductCommon
{
product2_specific;
}

**Comment by elado** [comment]
Not currently, though pull requests are welcome.

**Comment by pcompassion** [comment]
I implemented this and was about to do pull requests. but found it's already there in current version. 

relavant bits of codes are .. 

JastorRuntimeHelper.m
    NSArray\* arr = [JastorRuntimeHelper propertyNames:class_getSuperclass(klass)];
    [propertyNamesArray addObjectsFromArray:arr];

```
//this will support traversing the inheritance chain
return [self propertyClassForPropertyName:propertyName ofClass:class_getSuperclass(klass)];
```

**Comment by elado** [comment]
Oh cool. Thanks @yosit for that :)

**Comment by yosit** [comment]
;)  you are welcome.

**Comment by lwheng** [comment]
Hi @yosit , do you have a working example?
