### ISSUE TITLE
Add option to retail nil attributes.

### ISSUE THREAD

**Issue by Satshabad** [elado/jastor#4]
Is there anyway you could add an option somewhere so that nil attributes are converted to JSON keys with the value null? This would be great for the case when a missing key is not semantically equivalent to a null value for an object. 

If you want to point me in the right direction I can try to do this myself. I saw several `if attr == nil` comparisons, but I'm not sure what else they are doing. Thanks!

**Comment by yosit** [comment]
I think you would to avoid that since it's making the Json too big and  there is a different between how Json frameworks treat null and missing values.
In objc null in Json would be converted to [NSNull null] value which is a pain to handle.
—

**Comment by Satshabad** [comment]
Ah I see what you mean, but I think am suggesting the inverse.

Say we have a class Product and it has a few attributes, some of which are nil and some of which are not. Then when I want to turn it into json, I'd like the nil attributes to be turned to null in the json representation.

Or was that what you meant?

Thanks

**Comment by yosit** [comment]
The best practice is to omit those values if they are nil.
—
